### ISSUE TITLE
Title bar transparency

### ISSUE THREAD

**Issue by vkamelin** [bsundman/Yosembiance#18] opened 2016-02-01 13:08 UTC
Title bar has transparent area

**Comment by bsundman** [comment] 2016-02-01 16:06
I'm not sure exactly what you're talking about, could you add a screenshot?

**Comment by serhiinkh** [comment] 2016-02-03 21:44
@bsundman Hi, have same issue. 
![issue](https://cloud.githubusercontent.com/assets/2728287/12798009/c6e82ffe-cacf-11e5-8532-1b75093403b4.png)

**Comment by bsundman** [comment] 2016-02-04 03:59
I've just tested with Ubuntu 14.04 and 15.10 and am not getting this transparency.  What version of Ubuntu are you using?  Is this happening with the latest master branch?  Could you let me know if any of the previous branches have this issue?

**Comment by bsundman** [comment] 2016-02-04 05:07
Could you also let me know if this happens with the 1.1 branch?

**Comment by serhiinkh** [comment] 2016-02-05 00:22
@bsundman Hello i'm using Ubuntu 15.10 amd64, i checked this commit 44d1330 and there is issue. I did little research and get workaround for this. 
Changing this line 
https://github.com/bsundman/Yosembiance/blob/b98781a2fd47685de8bf6923fc6b567b597fca7e/Yosembiance-Ubuntu-Blue/gtk-3.0/apps/unity.css#L23 
to `border: 1px solid rgba (0, 0, 0, 0.01);` solve this issue for me.

**Comment by bsundman** [comment] 2016-02-05 03:23
Thanks!  That could have taken me forever to find and I really haven't had much time lately.  I have pushed the fix, can you test it for me and make sure it works now?

Could you let me know if commenting out or deleting that border line completely also fixes that bug?  I can't test it since I haven't been able to reproduce the bug.

**Comment by serhiinkh** [comment] 2016-02-06 21:54
Hello, bug is fixed. 

If delete this line bug is back.
If you write it like `border: 1px solid transparent;` or `border: 0px solid rgba (0, 0, 0, 0.01);` bug is back also if border-radius rule will be `border-radius: 0;` or not at all bug is back; so you need set border-radius to some positive number like 0.01% if you want sharp borders.

It looks like some libraries/software conflict because you have same os version.

**Comment by bsundman** [comment] 2016-02-08 17:43
Ok, thanks for testing that for me.

**Closed as completed by bsundman** 2016-02-08 17:43 UTC
